apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
data:
  POSTGRES_DB: postgres
  POSTGRES_HOST: database-1.cq0ysrg6qlgy.us-east-1.rds.amazonaws.com
  AWS_REGION: us-east-1
  JWT_SECRET: testing
  AWS_PROFILE: default
  AWS_BUCKET: mohamed-073321978685-project-dev
  URL: http://ac1188c04ea1342fe884ce010c8a009d-1630013184.us-west-2.elb.amazonaws.com